spring.application.name=salesforce-crud-backend

# SERVER

server.port=${PORT:8080}


# SALESFORCE

salesforce.login-url=https://login.salesforce.com

salesforce.client-id=${SALESFORCE_CLIENT_ID}

salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}

salesforce.callback-url=${SALESFORCE_CALLBACK_URL}

salesforce.api-version=v67.0


# SESSION COOKIE

server.servlet.session.cookie.http-only=true

server.servlet.session.cookie.same-site=none

server.servlet.session.cookie.secure=true


# LOGGING

logging.level.org.springframework.web=INFO

logging.level.com.salesforce.backend=INFO