spring.application.name=salesforce-crud-backend

# SERVER

server.port=${PORT:8080}
server.address=0.0.0.0


# SALESFORCE

salesforce.login-url=https://login.salesforce.com

salesforce.client-id=${SALESFORCE_CLIENT_ID}

salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}

salesforce.callback-url=${SALESFORCE_CALLBACK_URL}

salesforce.api-version=v67.0


# SESSION COOKIE

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.partitioned=true


# CORS

spring.web.cors.allowed-origins=${FRONTEND_URL}
spring.web.cors.allowed-methods=GET,POST,PATCH,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true


# LOGGING

logging.level.org.springframework.web=INFO
logging.level.com.salesforce.backend=INFO